name: Update Checker

on:  
  schedule:
    - cron: '45 13 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check for updates
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { data: ls } = await github.rest.packages.getPackageForUser({
              package_type: 'container',
              package_name: 'tvheadend',
              username: 'linuxserver',
            });
            
            const { data: jk } = await github.rest.packages.getPackageForUser({
              package_type: 'container',
              package_name: 'tvheadend',
              username: 'jakobkukla',
            });
            
            if (ls.updated_at > jk.updated_at) {
              const result = await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 6452595,
                ref: context.ref,
              }).catch(error => error).then(response => {
                core.debug(response);
                if (response.status !== 204) {
                  core.setFailed(`create workflow_dispatch received status code ${response.status}`);
                };
              });             
            }
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prevent GitHub actions from going stale
        uses: gautamkrishnar/keepalive-workflow@v1
